'use strict';

// tests for currentTime
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('currentTime', '/handler.js', 'endpoint');

describe('currentTime', () => {
  before((done) => {
    done();
  });

  it('not empty and 200', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
    expect(response.statusCode).to.be.equal(200);
  });
});
