service: sls-ci-cd

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-mocha-plugin

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: check
          method: get
